### ISSUE TITLE
Migrated: Facade to Architecture service

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#6]
Service migrated, however Primary Service on Proposal Summary not appearing. (note that Partner not added to this service, however other primary key data points not displayed).

![image](https://user-images.githubusercontent.com/93557524/155093506-306dd9e5-1c8e-4ba3-a852-0999786556ff.png)

![image](https://user-images.githubusercontent.com/93557524/155093728-a2e32fbb-da4a-4faa-b644-c0c589fb0016.png)

**Comment by JarrodWil** [comment]
@herbgdestined any update on this one? A glitch in the matrix?

**Comment by herbgdestined** [comment]
Hi @JarrodWil  will update before lunch on fix, the patch missed out the Design Office, Partner in Charge, and Design Leader.

**Comment by herbgdestined** [comment]
Hi @JarrodWil this has been fixed, kindly check on your end and let us know.

**Comment by JarrodWil** [comment]
Thanks. 

Before I close, can you advise how this got fixed so I can see if there are other occurrences please?

**Comment by herbgdestined** [comment]
Hi @JarrodWil when we update/patch the Proposal we did not include the Design Office, Partner in Charge, and Design Leader. Because we turn off all automations and validations during this process, those fields were left blank.

Our plan is to include those fields on the patch. Will explain more on the meeting if needed.

**Comment by JarrodWil** [comment]
reviewed and closed
